update:
  - platform: http_request
    id: update_http_request
    name: Firmware
    # source: https://raw.githubusercontent.com/AppliedSensorCo/ASC-product-code/main/SlumberTek/SlumberTek.json
    source: https://raw.githubusercontent.com/beausmith/ASC-product-code/main/SlumberTek/SlumberTek.json

dashboard_import:
  # package_import_url: github://AppliedSensorCo/ASC-product-code/SlumberTek/SlumberTek_ESPHome.yaml@main
  # package_import_url: github://AppliedSensorCo/ASC-product-code/SlumberTek/SlumberTek_ESPHome.yaml@beta
  # package_import_url: github://beausmith/ASC-product-code/SlumberTek/SlumberTek_ESPHome.yaml@main
  package_import_url: github://beausmith/ASC-product-code/SlumberTek/SlumberTek_ESPHome.yaml@beta
  import_full_config: false

packages:
  device_base: !include common/slumbertek_base.yaml
